services:
  tgbot:
    platform: linux/amd64
    container_name: tg-save-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: tg-save-redis
    restart: unless-stopped